services:
  # -------------------------------------------------------------
  # USER MONGODB
  # -------------------------------------------------------------
  user-db:
    image: mongo:7.0
    container_name: mongodb_user
    restart: always
    env_file:
      - ../user/.env
    ports:
      - "27017:27017"
    volumes:
      - user_mongodb_data:/data/db

  # -------------------------------------------------------------
  # PRODUCT MONGODB
  # -------------------------------------------------------------
  product-db:
    image: mongo:7.0
    container_name: mongodb_product
    restart: always
    env_file:
      - ../product/.env
    ports:
      - "27018:27017" # Exposed locally on 27018
    volumes:
      - product_mongodb_data:/data/db
  kafka:
    image: apache/kafka:latest
    container_name: kafka
    restart: unless-stopped

    ports:
      - "9092:9092"

    environment:
      # Kafka runs as both Broker and Controller
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller

      # Internal Kafka communication
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093

      # Address clients use to connect
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092

      # Controller communication
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT

      # KRaft quorum
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

      # Single broker development configuration
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

      # Useful for development
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

    volumes:
      - kafka_data:/var/lib/kafka/data


volumes:
  user_mongodb_data:
  product_mongodb_data:
  kafka_data:
